name: Deploy

on:
  workflow_dispatch:
  push:
    branches: main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository
    steps:
      - name: Setup Repository
        uses: actions/checkout@v3
      - name: Install `pnpm`
        run: npm install -g pnpm
      - name: Install `client` Dependencies
        run: pnpm install
        working-directory: client
      - name: Build Project
        run: pnpm build
        working-directory: client
      - name: Setup Deployment Folder
        run: |
          mkdir deploy
          mkdir deploy/client
          mkdir deploy/client/src
          mv -v client/dist/ deploy/client/
          mv -v client/src/models/ deploy/client/src/
          mv -v server/ deploy/
      - name: Print the Deployment Folder
        run: |
          ls -l deploy
          ls -l deploy/server
          ls -l deploy/client/dist
          ls -l deploy/client/src/models/
      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: palai
          root: deploy
          entrypoint: ./server/src/main.ts
          import-map: ./server/deno.json
